# Acceptable values for true: true, 1, yes
# Acceptable values for false: false, 0, no

#===============================================================================
# main device config

Device:
    # Name of the device on the network.
    Name: WifiWeatherClock

#===============================================================================
# Control how the ESP coprocessor will start and operate.

Coprocessor:

    # Should the ESP32 automatically attempt to connect to an access point at startup?
    # If set to true, wifi.yaml credentials must be stored in the device.

    AutomaticallyStartNetwork: false

    # Should the ESP32 automatically reconnect to the configured access point?
    AutomaticallyReconnect: false

    # Maximum number of retry attempts for connections etc. before an error code is returned.
    MaximumRetryCount: 5

# Network configuration.
Network:

    # Automatically attempt to get the time at startup?
    GetNetworkTimeAtStartup: 1

    # Time synchronization period in seconds.
    NtpRefreshPeriod: 600

    # Name of the NTP servers.
    NtpServers:
        - time.google.com
        - time1.google.com
        - time2.google.com
        - time3.google.com

    # IP addresses of the DNS servers.
    DnsServers:
        - 142.103.1.1
        - 65.39.139.53
